# HOW TO: Easy Visualization of Molecules.

Greetings everyone!

I've seen many people ask for a simple yet elegant visualization tool for the [Predicting Molecular Properties](https://www.kaggle.com/c/champs-scalar-coupling/overview) challenge. Therefore, I'm going to explain in this Kernel how to install and use **ase**, which is a python module that allows one to work with atoms and molecules. 

It is available on gitlab: [ase](https://gitlab.com/ase/ase).

The first thing we need to do is to install **ase** on our Kernel. To do that, just click on the *Settings* tab on the right panel, then click on *Install...*, right next to *Packages*. In the *pip package name* entry, just write **ase** then hit *Install Package*.

Kaggle is going to do its things then restart the Kernel. **ase** should then be installed! Let's check this:

In [57]:
import ase
import numpy as np
import networkx as nx
from rdkit import Chem
from rdkit.Chem import ChemicalFeatures
from rdkit import RDConfig
import os
from os import listdir
from os.path import isfile, join
import rdkit

It worked! 

Now let's visualize one of the molecule from the structures.csv file:

In [3]:
import pandas as pd

struct_file = pd.read_csv('data/structures.csv')

Now we select a random molecule from this file:

In [5]:
import random

# Select a molecule
random_molecule = random.choice(struct_file['molecule_name'].unique())
molecule = struct_file[struct_file['molecule_name'] == random_molecule]
display(molecule)

molecule_name  atom_index atom         x         y         z
1668382  dsgdb9nsd_096151           0    C  0.012196  1.554109  0.087176
1668383  dsgdb9nsd_096151           1    C -0.005880  0.031981 -0.010751
1668384  dsgdb9nsd_096151           2    C  0.527745 -0.463053 -1.370252
1668385  dsgdb9nsd_096151           3    C  0.151136 -1.902148 -1.672034
1668386  dsgdb9nsd_096151           4    O  1.190671 -2.810075 -2.056153
1668387  dsgdb9nsd_096151           5    C  0.548686 -3.011568 -0.792670
1668388  dsgdb9nsd_096151           6    C  1.351764 -2.772909  0.473882
1668389  dsgdb9nsd_096151           7    C  0.659281 -1.799868  1.439610
1668390  dsgdb9nsd_096151           8    O  0.787225 -0.439458  1.074029
1668391  dsgdb9nsd_096151           9    H  1.028769  1.932478 -0.060365
1668392  dsgdb9nsd_096151          10    H -0.637123  1.999854 -0.671892
1668393  dsgdb9nsd_096151          11    H -0.330387  1.872687  1.074748
1668394  dsgdb9nsd_096151          12    H -1.041770 -0.326809  0.121368
1668395  dsgdb9nsd_096151          13    H  0.146584  0.183984 -2.168306
1668396  dsgdb9nsd_096151          14    H  1.617521 -0.364059 -1.367040
1668397  dsgdb9nsd_096151          15    H -0.768852 -2.029624 -2.245255
1668398  dsgdb9nsd_096151          16    H -0.103856 -3.886227 -0.771494
1668399  dsgdb9nsd_096151          17    H  1.520780 -3.726954  0.986911
1668400  dsgdb9nsd_096151          18    H  2.334165 -2.368568  0.212109
1668401  dsgdb9nsd_096151          19    H -0.404437 -2.069938  1.552933
1668402  dsgdb9nsd_096151          20    H  1.124183 -1.874616  2.428261

Next we need to retrieve the atomic coordinates in a numpy array form:

In [6]:
# Get atomic coordinates
atoms = molecule.iloc[:, 3:].values
print(atoms)

[[ 0.01219636  1.55410948  0.08717552]
 [-0.00588043  0.03198091 -0.01075086]
 [ 0.52774516 -0.46305299 -1.37025224]
 [ 0.15113624 -1.9021482  -1.67203404]
 [ 1.19067087 -2.81007527 -2.05615339]
 [ 0.54868595 -3.01156781 -0.79266957]
 [ 1.35176371 -2.77290947  0.47388243]
 [ 0.65928068 -1.79986844  1.43960953]
 [ 0.78722529 -0.43945779  1.0740292 ]
 [ 1.0287693   1.93247798 -0.06036475]
 [-0.63712309  1.99985403 -0.67189232]
 [-0.3303865   1.87268738  1.07474842]
 [-1.04177016 -0.32680882  0.12136842]
 [ 0.1465838   0.18398418 -2.16830559]
 [ 1.6175213  -0.36405906 -1.36704023]
 [-0.76885172 -2.02962404 -2.24525462]
 [-0.10385582 -3.88622713 -0.7714938 ]
 [ 1.52078027 -3.72695419  0.98691095]
 [ 2.33416494 -2.36856832  0.21210909]
 [-0.40443696 -2.06993796  1.55293263]
 [ 1.12418334 -1.87461637  2.42826097]]


The last thing we need is the atomic symbols:

In [7]:
# Get atomic symbols
symbols = molecule.iloc[:, 2].values
print(symbols)

['C' 'C' 'C' 'C' 'O' 'C' 'C' 'C' 'O' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H'
 'H' 'H' 'H']


Finally, let's put everything into something that **ase** can process:

In [8]:
from ase import Atoms
import ase.visualize

system = Atoms(positions=atoms, symbols=symbols)

ase.visualize.view(system, viewer="x3d")

TADA!!!

You can rotate the molecule with a left click, translate it with a middle click, and zoom in or out using right click. 

All this can be summarized in a single function:

In [9]:
def view(molecule):
    # Select a molecule
    mol = struct_file[struct_file['molecule_name'] == molecule]
    
    # Get atomic coordinates
    xcart = mol.iloc[:, 3:].values
    
    # Get atomic symbols
    symbols = mol.iloc[:, 2].values
    
    # Display molecule
    system = Atoms(positions=xcart, symbols=symbols)
    print('Molecule Name: %s.' %molecule)
    return ase.visualize.view(system, viewer="x3d")

random_molecule = random.choice(struct_file['molecule_name'].unique())
view(random_molecule)

Molecule Name: dsgdb9nsd_096072.


In [23]:
graph_file='data/qm9/dsC702H10nsd/dsC7O2H10nsd_0005.xyz'

In [24]:
with open(graph_file,'r') as f:
        # Number of atoms
        na = int(f.readline())

        # Graph properties
        properties = f.readline()
        
        atom_properties = []
        # Atoms properties
        for i in range(na):
            a_properties = f.readline()
            a_properties = a_properties.replace('.*^', 'e')
            a_properties = a_properties.replace('*^', 'e')
            a_properties = a_properties.split()
            atom_properties.append(a_properties)
        atom_properties=np.array(atom_properties)
system = Atoms(positions=atom_properties[:,1:4], symbols=atom_properties[:,0])
ase.visualize.view(system, viewer="x3d")

In [26]:
def init_graph(prop):
    
    prop = prop.split()
    g_tag = prop[0]
    g_index = int(prop[1])
    g_A = float(prop[2])
    g_B = float(prop[3]) 
    g_C = float(prop[4]) 
    g_mu = float(prop[5])
    g_alpha = float(prop[6]) 
    g_homo = float(prop[7])
    g_lumo = float(prop[8]) 
    g_gap = float(prop[9])
    g_r2 = float(prop[10])
    g_zpve = float(prop[11]) 
    g_U0 = float(prop[12]) 
    g_U = float(prop[13])
    g_H = float(prop[14])
    g_G = float(prop[15])
    g_Cv = float(prop[16])

    labels = [g_mu, g_alpha, g_homo, g_lumo, g_gap, g_r2, g_zpve, g_U0, g_U, g_H, g_G, g_Cv]
    return nx.Graph(tag=g_tag, index=g_index, A=g_A, B=g_B, C=g_C, mu=g_mu, alpha=g_alpha, homo=g_homo,
                    lumo=g_lumo, gap=g_gap, r2=g_r2, zpve=g_zpve, U0=g_U0, U=g_U, H=g_H, G=g_G, Cv=g_Cv), labels

In [45]:
def qm9_nodes(g, hydrogen=True):
    h = []
    for n, d in g.nodes_iter(data=True):
        h_t = []
        # Atom type (One-hot H, C, N, O F)
        h_t += [int(d['a_type'] == x) for x in ['H', 'C', 'N', 'O', 'F']]
        # Atomic number
        h_t.append(d['a_num'])
        # Partial Charge
        h_t.append(d['pc'])
        # Acceptor
        h_t.append(d['acceptor'])
        # Donor
        h_t.append(d['donor'])
        # Aromatic
        h_t.append(int(d['aromatic']))
        # Hybradization
        h_t += [int(d['hybridization'] == x) for x in [rdkit.Chem.rdchem.HybridizationType.SP, rdkit.Chem.rdchem.HybridizationType.SP2, rdkit.Chem.rdchem.HybridizationType.SP3]]
        # If number hydrogen is used as a
        if hydrogen:
            h_t.append(d['num_h'])
        h.append(h_t)
    return h

def qm9_edges(g, e_representation='raw_distance'):
    remove_edges = []
    e={}    
    for n1, n2, d in g.edges_iter(data=True):
        e_t = []
        # Raw distance function
        if e_representation == 'chem_graph':
            if d['b_type'] is None:
                remove_edges += [(n1, n2)]
            else:
                e_t += [i+1 for i, x in enumerate([rdkit.Chem.rdchem.BondType.SINGLE, rdkit.Chem.rdchem.BondType.DOUBLE,
                                                rdkit.Chem.rdchem.BondType.TRIPLE, rdkit.Chem.rdchem.BondType.AROMATIC])
                        if x == d['b_type']]
        elif e_representation == 'distance_bin':
            if d['b_type'] is None:
                step = (6-2)/8.0
                start = 2
                b = 9
                for i in range(0, 9):
                    if d['distance'] < (start+i*step):
                        b = i
                        break
                e_t.append(b+5)
            else:
                e_t += [i+1 for i, x in enumerate([rdkit.Chem.rdchem.BondType.SINGLE, rdkit.Chem.rdchem.BondType.DOUBLE,
                                                   rdkit.Chem.rdchem.BondType.TRIPLE, rdkit.Chem.rdchem.BondType.AROMATIC])
                        if x == d['b_type']]
        elif e_representation == 'raw_distance':
            if d['b_type'] is None:
                remove_edges += [(n1, n2)]
            else:
                e_t.append(d['distance'])
                e_t += [int(d['b_type'] == x) for x in [rdkit.Chem.rdchem.BondType.SINGLE, rdkit.Chem.rdchem.BondType.DOUBLE,
                                                        rdkit.Chem.rdchem.BondType.TRIPLE, rdkit.Chem.rdchem.BondType.AROMATIC]]
        else:
            print('Incorrect Edge representation transform')
            quit()
        if e_t:
            e[(n1, n2)] = e_t
    for edg in remove_edges:
        g.remove_edge(*edg)
    return nx.to_numpy_matrix(g), e

In [59]:
def xyz_graph_reader(graph_file):

    with open(graph_file,'r') as f:
        # Number of atoms
        na = int(f.readline())

        # Graph properties
        properties = f.readline()
        g, l = init_graph(properties)
        
        atom_properties = []
        # Atoms properties
        for i in range(na):
            a_properties = f.readline()
            a_properties = a_properties.replace('.*^', 'e')
            a_properties = a_properties.replace('*^', 'e')
            a_properties = a_properties.split()
            atom_properties.append(a_properties)
            #print(a_properties)

        # Frequencies
        f.readline()

        # SMILES
        smiles = f.readline()
        smiles = smiles.split()
        smiles = smiles[0]
        #print(smiles)
        m = Chem.MolFromSmiles(smiles)
        m = Chem.AddHs(m)
        fdef_name = os.path.join(RDConfig.RDDataDir, 'BaseFeatures.fdef')
        factory = ChemicalFeatures.BuildFeatureFactory(fdef_name)
        feats = factory.GetFeaturesForMol(m)
        # Create nodes
        for i in range(0, m.GetNumAtoms()):
            atom_i = m.GetAtomWithIdx(i)

            g.add_node(i, a_type=atom_i.GetSymbol(), a_num=atom_i.GetAtomicNum(), acceptor=0, donor=0,
                       aromatic=atom_i.GetIsAromatic(), hybridization=atom_i.GetHybridization(),
                       num_h=atom_i.GetTotalNumHs(), coord=np.array(atom_properties[i][1:4]).astype(np.float),
                       pc=float(atom_properties[i][4]))

        for i in range(0, len(feats)):
            if feats[i].GetFamily() == 'Donor':
                node_list = feats[i].GetAtomIds()
                for i in node_list:
                    g.node[i]['donor'] = 1
            elif feats[i].GetFamily() == 'Acceptor':
                node_list = feats[i].GetAtomIds()
                for i in node_list:
                    g.node[i]['acceptor'] = 1

        # Read Edges
        for i in range(0, m.GetNumAtoms()):
            for j in range(0, m.GetNumAtoms()):
                e_ij = m.GetBondBetweenAtoms(i, j)
                if e_ij is not None:
                    g.add_edge(i, j, b_type=e_ij.GetBondType(),
                               distance=np.linalg.norm(g.node[i]['coord']-g.node[j]['coord']))
                else:
                    # Unbonded
                    g.add_edge(i, j, b_type=None,
                               distance=np.linalg.norm(g.node[i]['coord'] - g.node[j]['coord']))
    h=qm9_nodes(g)
    g,e=qm9_edges(g)
    return g, h,e, l
g_,h_,e_,l_=xyz_graph_reader(graph_file)
print(g_)
print(h_)
print(e_)
print(l_)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.

I hope you enjoyed this little notebook!

Cheers

Boris D.